---
title: "DATA612 Final Proj Planning Doc"
author: "Michael O'Donnell"
date: "July 3, 2019"
output: html_document
---

## Assignment

Find an interesting dataset and describe the system you plan to build out. If you would like to use one of the datasets you have already worked with, you should add a unique element or incorporate additional data. (i.e. explicit features you scrape from another source, like image analysis on movie posters). The overall goal, however, will be to produce quality recommendations by extracting insights from a large dataset. You may do so using Spark, or another distributed computing method, OR by effectively applying one of the more advanced mathematical techniques we have covered. There is no preference for one over the other, as long as your recommender works! The planning document should be written up and published as a notebook on GitHub or in RPubs.Please submit the link in the Unit 4 folder, due Thursday, July 5.

## Goal

Build a recommender system for History and Biography books.

## Dataset

Goodreads data, History and Biography Genre

https://sites.google.com/eng.ucsd.edu/ucsdbookgraph/home

## Recommender System:

Item-Based Collaborative Filtering System.

Reason for IBCF recommender system: there are niches within the genre of History and Biography; American history, musician biographies, athlete biographies, etc. Oftentimes, a reader like to read multiple books within a specific niche. Hence, and Item-Based system will work well to suggest similar books to those a reader already enjoyed.

### Programming language: R